package marketsystem.gui;

import java.awt.Image;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import marketsystem.Product;
import marketsystem.database.CustomerRepository;
import marketsystem.database.ProductRepository;
import marketsystem.database.ReceiptRepository;

public class AddReciept extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddReciept.class.getName());
    ArrayList<Product> products = ProductRepository.getProducts();
    marketsystem.Receipt receipt = new marketsystem.Receipt();
    ImageIcon picture = new ImageIcon("image3.jpg");
    Image img = picture.getImage();
    Image scaled;
    private Object model;
    Sales maf;

    public AddReciept(Sales f) {
        initComponents();
        this.maf = f;
        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        setChoiceProducts();
        day_textf.setText(String.valueOf(LocalDate.now().getDayOfMonth()));
        year_textf.setText(String.valueOf(LocalDate.now().getYear()));
        month_textf.setText(String.valueOf(LocalDate.now().getMonthValue()));
    }

    public AddReciept() {
        initComponents();

        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        setChoiceProducts();
        day_textf.setText(String.valueOf(LocalDate.now().getDayOfMonth()));
        year_textf.setText(String.valueOf(LocalDate.now().getYear()));
        month_textf.setText(String.valueOf(LocalDate.now().getMonthValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        product_lbl = new javax.swing.JLabel();
        day_lbl = new javax.swing.JLabel();
        month_lbl = new javax.swing.JLabel();
        year_lbl = new javax.swing.JLabel();
        earned_poi_lbl = new javax.swing.JLabel();
        spent_poi_lbl = new javax.swing.JLabel();
        total_cost_lbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        day_textf = new javax.swing.JTextField();
        month_textf = new javax.swing.JTextField();
        year_textf = new javax.swing.JTextField();
        earned_poi_textf = new javax.swing.JTextField();
        spent_poi_textf = new javax.swing.JTextField();
        total_cost_textf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        prod_qua_lbl = new javax.swing.JLabel();
        pro_name_lbl = new javax.swing.JLabel();
        prod_quan_textf = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        add_btn1 = new javax.swing.JButton();
        add_btn2 = new javax.swing.JButton();
        day_lbl1 = new javax.swing.JLabel();
        cust_id = new javax.swing.JTextField();
        mainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product_lbl.setBackground(new java.awt.Color(250, 235, 215));
        product_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product_lbl.setText("Products :");
        product_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        product_lbl.setOpaque(true);
        jPanel1.add(product_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, 30));

        day_lbl.setBackground(new java.awt.Color(250, 235, 215));
        day_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        day_lbl.setText("Day     :");
        day_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        day_lbl.setOpaque(true);
        jPanel1.add(day_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        month_lbl.setBackground(new java.awt.Color(250, 235, 215));
        month_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        month_lbl.setText("Month :");
        month_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        month_lbl.setOpaque(true);
        jPanel1.add(month_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 30));

        year_lbl.setBackground(new java.awt.Color(250, 235, 215));
        year_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        year_lbl.setText("Year     :");
        year_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        year_lbl.setOpaque(true);
        jPanel1.add(year_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 30));

        earned_poi_lbl.setBackground(new java.awt.Color(250, 235, 215));
        earned_poi_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        earned_poi_lbl.setText("Earned Points :");
        earned_poi_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        earned_poi_lbl.setOpaque(true);
        jPanel1.add(earned_poi_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 30));

        spent_poi_lbl.setBackground(new java.awt.Color(250, 235, 215));
        spent_poi_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spent_poi_lbl.setText("Spent Points   :");
        spent_poi_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spent_poi_lbl.setOpaque(true);
        jPanel1.add(spent_poi_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, 30));

        total_cost_lbl.setBackground(new java.awt.Color(250, 235, 215));
        total_cost_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total_cost_lbl.setText("Total Cost       :");
        total_cost_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total_cost_lbl.setOpaque(true);
        jPanel1.add(total_cost_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 180, 30));

        jLabel10.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 46, 27));
        jLabel10.setText(" Add Reciept");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 260, 70));

        day_textf.setEditable(false);
        day_textf.setBackground(new java.awt.Color(58, 46, 27));
        day_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        day_textf.setForeground(new java.awt.Color(250, 235, 215));
        day_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(day_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, 30));

        month_textf.setEditable(false);
        month_textf.setBackground(new java.awt.Color(58, 46, 27));
        month_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        month_textf.setForeground(new java.awt.Color(250, 235, 215));
        month_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(month_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, 30));

        year_textf.setEditable(false);
        year_textf.setBackground(new java.awt.Color(58, 46, 27));
        year_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        year_textf.setForeground(new java.awt.Color(250, 235, 215));
        year_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(year_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 210, 30));

        earned_poi_textf.setEditable(false);
        earned_poi_textf.setBackground(new java.awt.Color(58, 46, 27));
        earned_poi_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        earned_poi_textf.setForeground(new java.awt.Color(250, 235, 215));
        earned_poi_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(earned_poi_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 210, 30));

        spent_poi_textf.setEditable(false);
        spent_poi_textf.setBackground(new java.awt.Color(58, 46, 27));
        spent_poi_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        spent_poi_textf.setForeground(new java.awt.Color(250, 235, 215));
        spent_poi_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(spent_poi_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 210, 30));

        total_cost_textf.setEditable(false);
        total_cost_textf.setBackground(new java.awt.Color(58, 46, 27));
        total_cost_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        total_cost_textf.setForeground(new java.awt.Color(250, 235, 215));
        total_cost_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        total_cost_textf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_cost_textfActionPerformed(evt);
            }
        });
        jPanel1.add(total_cost_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 210, 30));

        product_table.setAutoCreateRowSorter(true);
        product_table.setBackground(new java.awt.Color(250, 235, 215));
        product_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27)));
        product_table.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        product_table.setForeground(new java.awt.Color(58, 46, 27));
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Category", " Price", "Selling Points", "Purchasing Points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_table.setDragEnabled(true);
        product_table.setGridColor(new java.awt.Color(58, 46, 27));
        product_table.setRowHeight(25);
        product_table.setSelectionBackground(new java.awt.Color(251, 236, 216));
        product_table.setSelectionForeground(new java.awt.Color(58, 46, 27));
        product_table.setShowGrid(true);
        product_table.setShowHorizontalLines(true);
        product_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(product_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 510, 350));

        prod_qua_lbl.setBackground(new java.awt.Color(250, 235, 215));
        prod_qua_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prod_qua_lbl.setText("Quantity :");
        prod_qua_lbl.setOpaque(true);
        jPanel1.add(prod_qua_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 70, 20));

        pro_name_lbl.setBackground(new java.awt.Color(250, 235, 215));
        pro_name_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pro_name_lbl.setText("Product :");
        pro_name_lbl.setOpaque(true);
        jPanel1.add(pro_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 70, 20));

        prod_quan_textf.setBackground(new java.awt.Color(58, 46, 27));
        prod_quan_textf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prod_quan_textf.setForeground(new java.awt.Color(250, 235, 215));
        prod_quan_textf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(prod_quan_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 210, 20));

        add_btn.setBackground(new java.awt.Color(250, 235, 215));
        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_btn.setText("Add as points product");
        add_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 290, -1));

        save_btn.setBackground(new java.awt.Color(250, 235, 215));
        save_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save_btn.setText("Save");
        save_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 100, -1));

        back_btn.setBackground(new java.awt.Color(250, 235, 215));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 46, 27), 2, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 590, 100, -1));

        choice1.setBackground(new java.awt.Color(58, 46, 27));
        choice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        choice1.setForeground(new java.awt.Color(250, 235, 215));
        jPanel1.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 210, 20));

        add_btn1.setBackground(new java.awt.Color(250, 235, 215));
        add_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_btn1.setText("Add as cash product");
        add_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 290, -1));

        add_btn2.setBackground(new java.awt.Color(250, 235, 215));
        add_btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_btn2.setText("Add");
        add_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 290, -1));

        day_lbl1.setBackground(new java.awt.Color(250, 235, 215));
        day_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        day_lbl1.setText("Customer ID     :");
        day_lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        day_lbl1.setOpaque(true);
        jPanel1.add(day_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 30));

        cust_id.setBackground(new java.awt.Color(58, 46, 27));
        cust_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cust_id.setForeground(new java.awt.Color(250, 235, 215));
        cust_id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(cust_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 30));

        mainImage.setBackground(new java.awt.Color(255, 255, 255));
        mainImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(mainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed

        if (prod_quan_textf.getText().isBlank()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Quantity cannot be empty.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {
            Integer.parseInt(prod_quan_textf.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter a valid numeric value for the quantity.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }
        for (int i = 0; i < Integer.parseInt(prod_quan_textf.getText()); i++) {
            receipt.addProductPoints(products.get(choice1.getSelectedIndex()));
        }
        updateList();
    }//GEN-LAST:event_add_btnActionPerformed

    void updateList() {
        DefaultTableModel model = (DefaultTableModel) product_table.getModel();
        model.setRowCount(0);
        for (Product product : receipt.getProductPurchasedCash().keySet()) {
            model.addRow(new Object[]{
                product.getName(),
                receipt.getProductPurchasedCash().get(product),
                product.getCategory().getCategoryName(),
                product.getPrice(),
                0,
                product.getPurchasingPoints(),});
        }
        for (Product product : receipt.getProductsPoints().keySet()) {
            model.addRow(new Object[]{
                product.getName(),
                receipt.getProductPurchasedPoints().get(product),
                product.getCategory().getCategoryName(),
                0,
                product.getProductSellingPoints(),
                0,});
        }
        earned_poi_textf.setText(String.valueOf(receipt.getTotalPointsEarned()));
        spent_poi_textf.setText(String.valueOf(receipt.getTotalPointsSpent()));
        total_cost_textf.setText(String.valueOf(receipt.getTotalProductsCashCost()));
    }

    private void total_cost_textfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_cost_textfActionPerformed
        // TODO AddReciept your handling code here:

    }//GEN-LAST:event_total_cost_textfActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        if (cust_id.getText().isBlank() || (receipt.getProductPurchasedCash().isEmpty() && receipt.getProductPurchasedPoints().isEmpty())) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please fill in all required fields.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            marketsystem.Customer customer = CustomerRepository.getCustomerByID(Integer.parseInt(cust_id.getText()));
            if (customer.getCustomerID() == 0) {
                JOptionPane.showMessageDialog(
                        null,
                        "Customer ID does not exist in the system.",
                        "Not Found",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }

            receipt.setCustomer(customer);
            if (customer.getPointsBalance() < receipt.getTotalPointsSpent()) {
                JOptionPane.showMessageDialog(
                        null,
                        "The customer's points balance is insufficient.",
                        "Insufficient Points",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }
            HashMap<Product, Integer> productsAll = new HashMap<>();
            for (Product product : receipt.getProductPurchasedCash().keySet()) {
                productsAll.put(product, receipt.getProductPurchasedCash().get(product));
            }
            for (Product product : receipt.getProductPurchasedPoints().keySet()) {
                productsAll.put(product, receipt.getProductPurchasedPoints().get(product));
            }
            for (Product product : productsAll.keySet()) {
                Product productData = ProductRepository.getProductByID(product.getProductID());
                System.out.println(productData.getProductQuantity() + " " + productsAll.get(product));
                if (productData.getProductQuantity() < productsAll.get(product)) {
                    JOptionPane.showMessageDialog(
                            null,
                            "The available product quantity (" + productData.getProductQuantity() + ") units is insufficient.",
                            "Insufficient Quantity",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
            }
            ReceiptRepository.insertReceipt(receipt);
            JOptionPane.showMessageDialog(
                    null,
                    "Operation completed successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter a valid numeric value for the Customer ID.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        dispose();
        // TODO AddReciept your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void add_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btn1ActionPerformed
        if (prod_quan_textf.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Qunatity cannot be empty");
            return;
        }

        try {
            Integer.parseInt(prod_quan_textf.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter a valid numeric value for the quantity.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        for (int i = 0; i < Integer.parseInt(prod_quan_textf.getText()); i++) {
            receipt.addProductCash(products.get(choice1.getSelectedIndex()));
        }
        updateList();
    }//GEN-LAST:event_add_btn1ActionPerformed

    private void add_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btn2ActionPerformed
        // TODO AddReciept your handling code here:
    }//GEN-LAST:event_add_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddReciept().setVisible(true));
    }

    private void setChoiceProducts() {

        for (Product product : products) {
            choice1.add(product.getName());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton add_btn1;
    private javax.swing.JButton add_btn2;
    private javax.swing.JButton back_btn;
    private java.awt.Choice choice1;
    private javax.swing.JTextField cust_id;
    private javax.swing.JLabel day_lbl;
    private javax.swing.JLabel day_lbl1;
    private javax.swing.JTextField day_textf;
    private javax.swing.JLabel earned_poi_lbl;
    private javax.swing.JTextField earned_poi_textf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel month_lbl;
    private javax.swing.JTextField month_textf;
    private javax.swing.JLabel pro_name_lbl;
    private javax.swing.JLabel prod_qua_lbl;
    private javax.swing.JTextField prod_quan_textf;
    private javax.swing.JLabel product_lbl;
    private javax.swing.JTable product_table;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel spent_poi_lbl;
    private javax.swing.JTextField spent_poi_textf;
    private javax.swing.JLabel total_cost_lbl;
    private javax.swing.JTextField total_cost_textf;
    private javax.swing.JLabel year_lbl;
    private javax.swing.JTextField year_textf;
    // End of variables declaration//GEN-END:variables

}
