package marketsystem.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import marketsystem.Product;
import marketsystem.database.ProductRepository;
import marketsystem.database.ReceiptRepository;

public class Sales extends javax.swing.JFrame {

    ArrayList<marketsystem.Receipt> receipts = marketsystem.database.ReceiptRepository.getReceipts();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sales.class.getName());
    String dayCom = "Day", monthCom = "Month", yearCom = "Year";
    double total_txt = 0.0;
    ImageIcon picture = new ImageIcon("image3.jpg");
    Image img = picture.getImage();
    Image scaled;

    /**
     * Creates new form Sales
     */
    MainFrame mainf;

    public Sales(MainFrame mf) {
        initComponents();

        this.mainf = mf;
        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        setTable();
        view_all_table.getSelectionModel().addListSelectionListener(e -> {
            int row = view_all_table.getSelectedRow();

            if (row == -1) {
                return; // no row selected
            }
            int id = Integer.parseInt(view_all_table.getValueAt(row, 0).toString());
            ViewReceipt v = new ViewReceipt(this, ReceiptRepository.getReceiptByID(id));
            v.setVisible(true);
            dispose();
        });

    }

    public Sales() {
        initComponents();
        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        setTable();
        view_all_table.getSelectionModel().addListSelectionListener(e -> {
            int row = view_all_table.getSelectedRow();

            if (row == -1) {
                return; // no row selected
            }
            int id = Integer.parseInt(view_all_table.getValueAt(row, 0).toString());
            ViewReceipt v = new ViewReceipt(this, ReceiptRepository.getReceiptByID(id));
            v.setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total = new javax.swing.JTextField();
        title_lable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_all_table = new javax.swing.JTable();
        cmb_month = new javax.swing.JComboBox<>();
        cmb_year = new javax.swing.JComboBox<>();
        cmb_day = new javax.swing.JComboBox<>();
        btn_add_receipt = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        mainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total.setEditable(false);
        total.setBackground(new java.awt.Color(250, 235, 215));
        total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(58, 46, 27));
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 3));
        total.setOpaque(true);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 320, 40));

        title_lable.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        title_lable.setForeground(new java.awt.Color(58, 46, 27));
        title_lable.setText("   Receipt");
        getContentPane().add(title_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 210, 60));

        view_all_table.setAutoCreateRowSorter(true);
        view_all_table.setBackground(new java.awt.Color(250, 235, 215));
        view_all_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27)));
        view_all_table.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        view_all_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reciept Id", "Customer", "Day", "Month", "Year", "Earned Points", "Spent Points", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_all_table.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        view_all_table.setGridColor(new java.awt.Color(58, 46, 27));
        view_all_table.setSelectionBackground(new java.awt.Color(250, 235, 215));
        view_all_table.setShowHorizontalLines(true);
        view_all_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(view_all_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 940, -1));

        cmb_month.setBackground(new java.awt.Color(250, 235, 215));
        cmb_month.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cmb_month.setForeground(new java.awt.Color(58, 46, 27));
        cmb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmb_month.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 46, 27), 2, true));
        cmb_month.setOpaque(true);
        cmb_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_monthActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 100, -1));

        cmb_year.setBackground(new java.awt.Color(250, 235, 215));
        cmb_year.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cmb_year.setForeground(new java.awt.Color(58, 46, 27));
        cmb_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cmb_year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        cmb_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_yearActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 60, 90, -1));

        cmb_day.setBackground(new java.awt.Color(250, 235, 215));
        cmb_day.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cmb_day.setForeground(new java.awt.Color(58, 46, 28));
        cmb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmb_day.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        cmb_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_dayActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        btn_add_receipt.setBackground(new java.awt.Color(250, 235, 215));
        btn_add_receipt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add_receipt.setText("Add Receipt");
        btn_add_receipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 3));
        btn_add_receipt.setOpaque(true);
        btn_add_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_receiptActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 360, 40));

        btn_back.setBackground(new java.awt.Color(250, 235, 215));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 3));
        btn_back.setOpaque(true);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 60, 40));
        getContentPane().add(mainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_monthActionPerformed
        // TODO AddReciept your handling code here:
        monthCom = String.valueOf(cmb_month.getSelectedItem());
        setTable();
    }//GEN-LAST:event_cmb_monthActionPerformed

    private void btn_add_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_receiptActionPerformed
        AddReciept p = new AddReciept(this);
        p.setVisible(true);
        this.setVisible(false);

        // TODO AddReciept your handling code here:
    }//GEN-LAST:event_btn_add_receiptActionPerformed

    private void setTable() {
        total_txt = 0;
        DefaultTableModel model = (DefaultTableModel) view_all_table.getModel();
        model.setRowCount(0);
        if (!monthCom.equals("Month") && !dayCom.equals("Day") && !yearCom.equals("Year")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getDay() == Integer.parseInt(dayCom) && receipt.getYear() == Integer.parseInt(yearCom) && receipt.getMonth() == Integer.parseInt(monthCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!monthCom.equals("Month") && !dayCom.equals("Day")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getDay() == Integer.parseInt(dayCom) && receipt.getMonth() == Integer.parseInt(monthCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!monthCom.equals("Month") && !yearCom.equals("Year")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getYear() == Integer.parseInt(yearCom) && receipt.getMonth() == Integer.parseInt(monthCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!dayCom.equals("Day") && !yearCom.equals("Year")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getDay() == Integer.parseInt(dayCom) && receipt.getYear() == Integer.parseInt(yearCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!monthCom.equals("Month")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getMonth() == Integer.parseInt(monthCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!dayCom.equals("Day")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getDay() == Integer.parseInt(dayCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else if (!yearCom.equals("Year")) {
            for (marketsystem.Receipt receipt : receipts) {
                if (receipt.getYear() == Integer.parseInt(yearCom)) {
                    model.addRow(new Object[]{
                        receipt.getReceiptId(),
                        receipt.getCustomer().getCustomerName(),
                        receipt.getDay(),
                        receipt.getMonth(),
                        receipt.getYear(),
                        receipt.getEarnedPoints(),
                        receipt.getSpentPoints(),
                        receipt.getTotalCost()
                    });
                    total_txt += receipt.getTotalCost();
                }
            }
        } else {
            for (marketsystem.Receipt receipt : receipts) {
                model.addRow(new Object[]{
                    receipt.getReceiptId(),
                    receipt.getCustomer().getCustomerName(),
                    receipt.getDay(),
                    receipt.getMonth(),
                    receipt.getYear(),
                    receipt.getEarnedPoints(),
                    receipt.getSpentPoints(),
                    receipt.getTotalCost()
                });
                total_txt += receipt.getTotalCost();

            }
        }
        total.setText("Total Returns: " + String.format("%.2f", total_txt));

    }

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        dispose();      // TODO AddReciept your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    private void cmb_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_dayActionPerformed
        // TODO AddReciept your handling code here:
        dayCom = String.valueOf(cmb_day.getSelectedItem());
        setTable();
    }//GEN-LAST:event_cmb_dayActionPerformed

    private void cmb_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_yearActionPerformed
        // TODO AddReciept your handling code here:
        yearCom = String.valueOf(cmb_year.getSelectedItem());
        setTable();
    }//GEN-LAST:event_cmb_yearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_receipt;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> cmb_day;
    private javax.swing.JComboBox<String> cmb_month;
    private javax.swing.JComboBox<String> cmb_year;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel title_lable;
    private javax.swing.JTextField total;
    private javax.swing.JTable view_all_table;
    // End of variables declaration//GEN-END:variables
}
