package marketsystem.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame.*;
import javax.swing.table.DefaultTableModel;
import marketsystem.Product;
import marketsystem.database.ReceiptRepository;

public class ViewReceipt extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewReceipt.class.getName());

    /**
     * Creates new form ViewReceipt
     */
    ImageIcon picture = new ImageIcon("image3.jpg");
    Image img = picture.getImage();
    Image scaled;

    Sales mas;

    public ViewReceipt(Sales s, marketsystem.Receipt receipt) {
        initComponents();
        this.mas = s;
        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        v_rec_id_txt.setText(String.valueOf(receipt.getReceiptId()));
        v_cus_id_txt1.setText(receipt.getCustomer().getCustomerName());
        v_day_txt.setText(String.valueOf(receipt.getDay()));
        v_year_text.setText(String.valueOf(receipt.getYear()));
        v_month_txt.setText(String.valueOf(receipt.getMonth()));
        v_total_cost_text.setText(String.valueOf(receipt.getTotalCost()));
        v_earned_text.setText(String.valueOf(receipt.getEarnedPoints()));
        v_spent_txt.setText(String.valueOf(receipt.getSpentPoints()));
        showList(receipt);
    }

    public ViewReceipt() {
        initComponents();

        this.setLocationRelativeTo(null);
        scaled
                = img.getScaledInstance(mainImage.getWidth(), mainImage.getHeight(), Image.SCALE_SMOOTH);
        mainImage.setIcon(new ImageIcon(scaled));
        marketsystem.Receipt receipt = ReceiptRepository.getReceiptByID(0);
        v_rec_id_txt.setText(String.valueOf(receipt.getReceiptId()));
        v_cus_id_txt1.setText(receipt.getCustomer().getCustomerName());
        v_day_txt.setText(String.valueOf(receipt.getDay()));
        v_year_text.setText(String.valueOf(receipt.getYear()));
        v_month_txt.setText(String.valueOf(receipt.getMonth()));
        v_total_cost_text.setText(String.valueOf(receipt.getTotalCost()));
        v_earned_text.setText(String.valueOf(receipt.getEarnedPoints()));
        v_spent_txt.setText(String.valueOf(receipt.getSpentPoints()));
        showList(receipt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_table = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        v_cus_id_lbl = new javax.swing.JLabel();
        v_year_lbl = new javax.swing.JLabel();
        v_earned_lbl = new javax.swing.JLabel();
        v_spent_lbl = new javax.swing.JLabel();
        v_total_cost_lbl = new javax.swing.JLabel();
        v_rec_id_lbl = new javax.swing.JLabel();
        v_day_txt = new javax.swing.JLabel();
        v_year_text = new javax.swing.JLabel();
        v_earned_text = new javax.swing.JLabel();
        v_spent_txt = new javax.swing.JLabel();
        v_total_cost_text = new javax.swing.JLabel();
        v_rec_id_txt = new javax.swing.JLabel();
        v_day_lbl = new javax.swing.JLabel();
        v_month_txt = new javax.swing.JLabel();
        v_month_lbl = new javax.swing.JLabel();
        v_cus_id_txt1 = new javax.swing.JLabel();
        mainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_lbl.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        title_lbl.setForeground(new java.awt.Color(58, 46, 27));
        title_lbl.setText("  View Receipt");
        jPanel1.add(title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 80));

        view_table.setAutoCreateRowSorter(true);
        view_table.setBackground(new java.awt.Color(250, 235, 215));
        view_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        view_table.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        view_table.setForeground(new java.awt.Color(58, 46, 27));
        view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Category", "Price", "Point"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_table.setDragEnabled(true);
        view_table.setGridColor(new java.awt.Color(58, 46, 27));
        view_table.setShowGrid(true);
        view_table.setShowHorizontalLines(true);
        view_table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(view_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 610, 510));

        back_btn.setBackground(new java.awt.Color(250, 235, 215));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(58, 46, 27));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 46, 27), 2, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 90, 30));

        v_cus_id_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_cus_id_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_cus_id_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_cus_id_lbl.setText("Customer Name:");
        v_cus_id_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        v_cus_id_lbl.setOpaque(true);
        jPanel1.add(v_cus_id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        v_year_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_year_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_year_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_year_lbl.setText("Year :");
        v_year_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 45, 26), 2));
        v_year_lbl.setOpaque(true);
        jPanel1.add(v_year_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 30));

        v_earned_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_earned_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_earned_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_earned_lbl.setText("Earned Points:");
        v_earned_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        v_earned_lbl.setOpaque(true);
        jPanel1.add(v_earned_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 30));

        v_spent_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_spent_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_spent_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_spent_lbl.setText("Spent Points  :");
        v_spent_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        v_spent_lbl.setOpaque(true);
        jPanel1.add(v_spent_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 160, 30));

        v_total_cost_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_total_cost_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_total_cost_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_total_cost_lbl.setText("Total Cost :");
        v_total_cost_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        v_total_cost_lbl.setOpaque(true);
        jPanel1.add(v_total_cost_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 90, 30));

        v_rec_id_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_rec_id_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_rec_id_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_rec_id_lbl.setText("Receipt Id :");
        v_rec_id_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 46, 27), 2));
        v_rec_id_lbl.setOpaque(true);
        jPanel1.add(v_rec_id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        v_day_txt.setBackground(new java.awt.Color(58, 46, 27));
        v_day_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_day_txt.setForeground(new java.awt.Color(250, 235, 215));
        v_day_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_day_txt.setOpaque(true);
        jPanel1.add(v_day_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 210, 30));

        v_year_text.setBackground(new java.awt.Color(58, 46, 27));
        v_year_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_year_text.setForeground(new java.awt.Color(250, 235, 215));
        v_year_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_year_text.setOpaque(true);
        jPanel1.add(v_year_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 210, 30));

        v_earned_text.setBackground(new java.awt.Color(58, 46, 27));
        v_earned_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_earned_text.setForeground(new java.awt.Color(250, 235, 215));
        v_earned_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_earned_text.setOpaque(true);
        jPanel1.add(v_earned_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 210, 30));

        v_spent_txt.setBackground(new java.awt.Color(58, 46, 27));
        v_spent_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_spent_txt.setForeground(new java.awt.Color(250, 235, 215));
        v_spent_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_spent_txt.setOpaque(true);
        jPanel1.add(v_spent_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 210, 30));

        v_total_cost_text.setBackground(new java.awt.Color(58, 46, 27));
        v_total_cost_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_total_cost_text.setForeground(new java.awt.Color(250, 235, 215));
        v_total_cost_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_total_cost_text.setOpaque(true);
        jPanel1.add(v_total_cost_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 210, 30));

        v_rec_id_txt.setBackground(new java.awt.Color(58, 46, 27));
        v_rec_id_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_rec_id_txt.setForeground(new java.awt.Color(250, 235, 215));
        v_rec_id_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_rec_id_txt.setOpaque(true);
        jPanel1.add(v_rec_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 30));

        v_day_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_day_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_day_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_day_lbl.setText("Day :");
        v_day_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 45, 26), 2));
        v_day_lbl.setOpaque(true);
        jPanel1.add(v_day_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 30));

        v_month_txt.setBackground(new java.awt.Color(58, 46, 27));
        v_month_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_month_txt.setForeground(new java.awt.Color(250, 235, 215));
        v_month_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_month_txt.setOpaque(true);
        jPanel1.add(v_month_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 210, 30));

        v_month_lbl.setBackground(new java.awt.Color(250, 235, 215));
        v_month_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v_month_lbl.setForeground(new java.awt.Color(58, 46, 27));
        v_month_lbl.setText("Month :");
        v_month_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 45, 26), 2));
        v_month_lbl.setOpaque(true);
        jPanel1.add(v_month_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 30));

        v_cus_id_txt1.setBackground(new java.awt.Color(58, 46, 27));
        v_cus_id_txt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v_cus_id_txt1.setForeground(new java.awt.Color(250, 235, 215));
        v_cus_id_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 235, 215)));
        v_cus_id_txt1.setOpaque(true);
        jPanel1.add(v_cus_id_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 210, 30));
        jPanel1.add(mainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 975, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewReceipt().setVisible(true));

    }

    void showList(marketsystem.Receipt receipt) {
        DefaultTableModel model = (DefaultTableModel) view_table.getModel();
        model.setRowCount(0);
        for (Product product : receipt.getProductPurchasedCash().keySet()) {
            model.addRow(new Object[]{
                product.getName(),
                receipt.getProductPurchasedCash().get(product),
                product.getCategory().getCategoryName(),
                product.getPrice(),
                0,
                product.getPurchasingPoints(),});
        }
        for (Product product : receipt.getProductsPoints().keySet()) {
            model.addRow(new Object[]{
                product.getName(),
                receipt.getProductPurchasedPoints().get(product),
                product.getCategory().getCategoryName(),
                0,
                product.getProductSellingPoints(),
                0,});
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JLabel v_cus_id_lbl;
    private javax.swing.JLabel v_cus_id_txt1;
    private javax.swing.JLabel v_day_lbl;
    private javax.swing.JLabel v_day_txt;
    private javax.swing.JLabel v_earned_lbl;
    private javax.swing.JLabel v_earned_text;
    private javax.swing.JLabel v_month_lbl;
    private javax.swing.JLabel v_month_txt;
    private javax.swing.JLabel v_rec_id_lbl;
    private javax.swing.JLabel v_rec_id_txt;
    private javax.swing.JLabel v_spent_lbl;
    private javax.swing.JLabel v_spent_txt;
    private javax.swing.JLabel v_total_cost_lbl;
    private javax.swing.JLabel v_total_cost_text;
    private javax.swing.JLabel v_year_lbl;
    private javax.swing.JLabel v_year_text;
    private javax.swing.JTable view_table;
    // End of variables declaration//GEN-END:variables
}
